DROP DATABASE IF EXISTS spotifysongsdb;
CREATE DATABASE spotifysongsdb;
USE spotifysongsdb;

DROP TABLE IF EXISTS PLAYLISTS;
CREATE TABLE PLAYLISTS(
	ID VARCHAR(50), 
    Name VARCHAR(200) UNIQUE,
    URI VARCHAR(300),
    PRIMARY KEY (ID, Name)
);

DROP TABLE IF EXISTS SONGS;
CREATE TABLE SONGS(
	Name VARCHAR(255) CHARACTER SET utf8mb4 PRIMARY KEY,
	Album VARCHAR(255) CHARACTER SET utf8mb4,
    Artist VARCHAR(255) CHARACTER SET utf8mb4,
    Cover VARCHAR(255),
    Link VARCHAR(255),
    ID VARCHAR(255),
    Preview VARCHAR(255),
    Playlist VARCHAR(200),
    FOREIGN KEY (Playlist) REFERENCES PLAYLIST(Name)
);
    
	
    
